### ISSUE TITLE
[Cub] Height of form elements vary

### ISSUE THREAD

**Issue by mmaismma** [Hermit-Tools/Thumbnail-Maker#22]
**Describe the bug**  
The height of the elements in the form is not fixed. When the height of the viewport is decreased (due to opening of a keyboard on mobile phones) their height decrease.

**To Reproduce**
Steps to reproduce the behavior :  
1. Open Cub's Contraption on a mobile device
2. Tap on "Enter episode number"
3. Your keyboard will open and you can see that height of all form elements has changed.

**Expected behavior**  
The height of the elements should be the same.

**Screenshots**  
Before:  
<img alt="Before opening keyboard" width="400px" src="https://user-images.githubusercontent.com/44745238/90619312-b918ba80-e22e-11ea-89f5-4a6e68ad86e0.png">
After:  
<img alt="After opening keyboard" width="400px" src="https://user-images.githubusercontent.com/44745238/90619350-c2a22280-e22e-11ea-9ca2-03e44cb94a2a.png">

**Comment by Sashankr** [comment]
Hey, can I try and fix this?

**Comment by mmaismma** [comment]
This issue has re-appeared in Cub's Contraption latest release.

**Comment by mmaismma** [comment]
This issue requires several fixes. I have stated some of the problems faced while fixing the issue.
- **Normal conditions**:
  ![hermit-tools github io_Thumbnail-Maker_cubfan135_ (2)](https://user-images.githubusercontent.com/44745238/100988064-49c49d80-3575-11eb-9f56-7dd2b264d6ce.png)
- **Applied `height: max-content` as @Sashankr mentioned in PR #25**:
  ![hermit-tools github io_Thumbnail-Maker_cubfan135_ (3)](https://user-images.githubusercontent.com/44745238/100988273-8e503900-3575-11eb-96f4-0b33f3c1a86c.png)
  As you can see the content gets cut.
- **Applied `overflow: auto`**:
  ![hermit-tools github io_Thumbnail-Maker_cubfan135_ (4)](https://user-images.githubusercontent.com/44745238/100989388-d3c13600-3576-11eb-8d52-460c08445f7e.png)
  You can scroll down but not up.

On applying `height: max-content`, these issues also occur.
- **The height of *Remove Background Image* button needs thinking**:
  ![image](https://user-images.githubusercontent.com/44745238/100990025-75488780-3577-11eb-866a-7884ab7942f9.png)
- **The *Download* button needs to be taller**:
  ![image](https://user-images.githubusercontent.com/44745238/100989976-6b268900-3577-11eb-8b1f-cb84da784b3b.png)

**Comment by Sashankr** [comment]
I will try to fix it before Sunday! I'm a bit busy with work!
Have a great day!

**Comment by mmaismma** [comment]
As you wish

**Comment by therealsylaucoin** [comment]
@mmaismma I should have time this week to take a stab at this.

**Comment by mmaismma** [comment]
> @mmaismma I should have time this week to take a stab at this.

Why not? No stress. Good luck!
