### ISSUE TITLE
[Cub] Dark mode should be remembered

### ISSUE THREAD

**Issue by mmaismma** [Hermit-Tools/Thumbnail-Maker#24]
**Description**
Cub's Contraption has a dark mode in the beta version. Issue #23 suggests enabling dark mode when the user uses it as the preferred theme. While that is smart, it is also smart to remember what mode the user chose.

**Possible solution(s)**
If the user has chosen dark mode, create and store a cookie. If the cookie exists, switch to dark mode. Clear the cookie when the user chooses light mode.

**Comment by alpeshyadav** [comment]
Hey, localstorage will also do the work. If you want I can make PR

**Comment by mmaismma** [comment]
You are 100% correct. Would be cool if you make a PR.

There are pros and cons of using both cookies and local storage. Although local storage is better for our case.

Cookies | Local Storage
--- | ---
Cookies can be used to automatically set dark mode on our other webpages/websites even if the user sets the theme on only one webpage. | Local storage is meant for client-side uses only. Cannot automatically toggle the dark mode on other webpages based on the user's input on only one page/site.
Cookies require extra HTTP request per item which require extra bandwidth and makes the loading slow. | Local storage is persistent data that is stored directly in the browser.
Cookies are tiresome to manage with JavaScript. Some people even have cookies disabled in their browsers. | Local storage data in JSON format, thus easy to parse.
In European Union countries, cookies require an *accept cookies* banner to display on the webpage. | No such thing exists for the uses of local storage.

We cannot use cookies against local storage for just one reason.

**Comment by alpeshyadav** [comment]
Cool

**Comment by alpeshyadav** [comment]
I didn't get it 

> what mode the user chose

I presume we should have a toggle button somewhere there. Correct me if I'm wrong.

**Comment by mmaismma** [comment]
Cub's Contraption has a dark mode in [the beta version](https://github.com/Hermit-Tools/Thumbnail-Maker/blob/master/Source/cubfan135/). Currently, it activates by typing *invert* while on the webpage. The function [`darken`](https://github.com/Hermit-Tools/Thumbnail-Maker/blob/master/Source/cubfan135/script.js#L113) triggers every time the theme is changed. It toggles *"dark"* in the body's class list and the rest is handled by CSS.

An example to close this issue:
<pre>
Store a key `theme` in the local storage
          with default value `light`.
                  ⬇
At the end of the function `darken()`,
check if `body.classList` contains "dark".         -YES➡   Change `theme`'s value to `dark`.
                NO⬇
   Change `theme`'s value to `light`.
</pre>
Add a piece of code in the `<head>`, to automatically match the page's theme to the specified theme in local storage.
<pre>
Check the `theme`'s value.            -`dark` ➡   Add `dark` to <body>'s class.
      `light` ⬇
     Do nothing.
</pre>

I hope it makes sense, feel free to ask for help. Adding a toggle button is not in the scope of this issue. This issue is only to deal with automatically switching to dark mode whenever the user (who has switched on dark mode) visits the page.

**Comment by alpeshyadav** [comment]
Thanks a lot. Will do it.
