### ISSUE TITLE
[Cub] Choose background cannot be focused with keyboard

### ISSUE THREAD

**Issue by mmaismma** [Hermit-Tools/Thumbnail-Maker#27]
**Description**
The *Choose Background* button can not be focused on by the keyboard. This is because the button is not an `input` nor `button` or anything stated *interactive* in the accessibility tree, it is rather a `label` and it's corresponding `input` is hidden by CSS.

**Possible solution(s)**
One possible solution is to add the attribute [`tabindex`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) to the `label` with value `0`.

**Comment by moody2times** [comment]
Hello,
I can take a look and fix it. Your solution sounds good but tabindex starts at 1 not 0. Please, assign it to me.

**Comment by mmaismma** [comment]
Why not? Make a pull request and submit it. Although, I would like to mention it to you that **`tabindex` can be any integer, even negative one, and zero**. Negative integers mean that the element cannot be focused at all. Zero means that the element will get focused with the keyboard but with the same tab position as it is in the code. Positive integers denote the customized position of the element, different than in the code.

`tabindex="0"` should be used to make a non-focusable element keyboard-focusable. For example, a `div` can not be focused by the keyboard. But a `div` with zero `tabindex` can be focused by the keyboard. This will thus allow the scrolling of the div with arrow keys.

Positive integers are discouraged from using. This is because they will cause many troubles to users who use accessibility tools. Since our code is written in a perfect logical sense, I will recommend using zero `tabindex` on the element.

**Comment by mmaismma** [comment]
A better solution would be to wrap the label in `<button>` and then style the element as we wish with CSS. This is because using `tabindex` does not register the element as focusable in the accessibility tree. This will cause trouble for ARIA users. `<button>` and, `<input>` are a few elements that are registered as tab-focusable in the accessibility tree. Using `tabindex="0"` is not bad, but using `<button>`  is even better.

**Comment by moody2times** [comment]
Alright, thanks for correcting me and thanks for the new suggestion.

**Comment by mmaismma** [comment]
Alright, I assigned you.
