### ISSUE TITLE
[Cub] Allow upload of background image by drag and drop

### ISSUE THREAD

**Issue by mmaismma** [Hermit-Tools/Thumbnail-Maker#29]
## Description
The first step to making a thumbnail with Cub's Contraption is to upload the background image. Currently, the only way to upload the image is to click on the *Choose Background* button and choose the image.  
Allowing the drag and drop upload of the background would be smart. Imagine **the user drags an image to the webpage, a UI shows that the user can drop the image to make it the background. And when the user drops the image, it becomes the new background.**

## Possible solution(s)
The HTML drag and drop API was made for this purpose. Listen to `dragover` and `drop` events on `window`.  
1. On `dragover`, append a `div` that spans all the window. Design that `div` properly (see Possible UI in Additional context).  
2. On `drop`, use the `dataTransfer` interface to get the first image as `bgInput`'s value.

**Possible function `ondrop`**:
```js
function dropHandler(e) {
  e.preventDefault(); // Prevent file(s) from being opened

  if (e.dataTransfer.item) {

    // Add the first image as bgInput's value
    for (let i = 0; i < e.dataTransfer.items.length; i++) {

      // Accept items only if they are files, not strings
      if (e.dataTransfer.items[i].kind === 'file') {
        if (e.dataTransfer.items[i].type.indexOf('image') === 0) {
          bgInput.value = e.dataTransfer.items[i].getAsFile();
          return;
        }
      }
    }
  }
}
```

## Additional context
Possible UI:  
![image](https://user-images.githubusercontent.com/44745238/95172077-7148f500-07d4-11eb-9b48-3a818390a0b1.png)

**Comment by nsandor-webDev** [comment]
I would like to work on this drag n drop script. Can you assign it to me?

**Comment by mmaismma** [comment]
Why not? My good deeds as are with you, write your best code ever and make a pull request when you are done. Don't hesitate to contact us in case.

**Comment by nsandor-webDev** [comment]
> Why not? My good deeds as are with you, write your best code ever and make a pull request when you are done. Don't hesitate to contact us in case.

May I ask what JS file can I code ? In direct cubfan123 folder or in source folder ? Thanks for answer !

**Comment by mmaismma** [comment]
Always commit all changes in the files under *Source/*.

**Comment by nsandor-webDev** [comment]
@mmaismma I'm done with it. Tomorrow I'll clear code, comment it.

**Comment by mmaismma** [comment]
I am not sure what do you mean by "I'll clear code, comment it." You have to make a pull request, right?

**Comment by nsandor-webDev** [comment]
> I am not sure what do you mean by "I'll clear code, comment it." You have to make a pull request, right?

Yes I know. I mean I'll simplify the code using variables, functions etc..And comment it for next development - if someone will do with this code he'll understand it.

**Comment by mmaismma** [comment]
Excited to see the code!
