### ISSUE TITLE
[Cub] Material Icons can sometimes appear as text

### ISSUE THREAD

**Issue by mmaismma** [Hermit-Tools/Thumbnail-Maker#47]
## Describe the bug
Ligatures implement material icons (a word is replaced by an icon, e.g. `share` to a share icon). Sometimes, not very rare, the words don't get converted into icons and give a very unpleasant look.

It may happen because of a slow internet connection due to which the request to _Material Icons font_ gets closed before the browser loads it completely. As a result, the words don't get converted.

## To Reproduce
It is somewhat random but the following steps reproduce the bug.
1. Open [Cub's Contraption](https://hermit-tools.github.io/Thumbnail-Maker/cubfan135/).
2. Open _DevTools_.
3. Go to the "Network" panel and change the connection to "Slow 3G".
4. Right-click on the refresh icon in the browser's UI and click on "Empty cache and hard refresh".
5. Once the refresh starts, stop it.
6. See the result.

## Expected behavior
Icons should load correctly.

## Browser information
Microsoft Edge 87.0.664.75 (Official build) (32-bit).

## Additional context
![image](https://user-images.githubusercontent.com/44745238/104460882-9e2b5600-55d4-11eb-96fe-254724a14f92.png)

See [Material Icons Guide by Google - Icon Font For The Web](https://google.github.io/material-design-icons/#icon-font-for-the-web) for information on how Material icons work.

### 1. Replace Material Icons with other options like Fluent Icons
This would differ from our material design though.
### 2. Add the Material Icons to our repo and serve them as SVG files
That's too much work in a long run. It may not be.
### 3. Use _pseudo-elements_ and _data attributes_ to serve the icons
Probably the best option. [Read more](https://css-tricks.com/ligature-icons/) on CSS Tricks.

**Comment by yurywektorovich** [comment]
Check out the pull request.
